### ISSUE TITLE
Add `bin` directory to the default list of packaged files

### ISSUE THREAD

**Issue by Fuco1** [melpa/package-build#25]
I think the convention is pretty wide spread, all packages that have a binary store it in a `bin` directory and adding that explicitly complicates things.

I'm pretty sure this wouldn't break anything and it would make packaging simpler.  Also it would fix issues like this: https://github.com/cask/cask/issues/395#issuecomment-418083153

**Comment by purcell** [comment]
In many cases elisp is part of a larger project, e.g. a language implementation which also has an Emacs major mode. I think blanket inclusion of `bin` would therefore be the wrong thing to do in the majority of cases.
