### ISSUE TITLE
`(package-build-all)` succeeds but prints about the building package failed

### ISSUE THREAD

**Issue by ramboman** [melpa/package-build#27]
`(package-build-all)` builds correctly the archive, but it prints:
```
...
Successfully built 0 of 1 packagesBuilding 1 packages failed:
```
at the end of the output.

Here is the structure of my personal melpa directory:
```
<personal-melpa-dir>
 |- archive
 |   \- (empty)
 |- recipes
 |   \- smex
 \- working
     \- (empty)
```

`recipes/smex`:
``` emacs-lisp
(smex :repo "nonsequitur/smex" :fetcher github)
```

`test.el`
``` emacs-lisp
#!emacs --script

(add-to-list 'load-path "<package-build-git-repo-dir>")

(require 'package-build)

(setq local-melpa-dir "<personal-melpa-dir>")
(setq package-build-archive-dir (expand-file-name "archive" local-melpa-dir))
(setq package-build-recipes-dir (expand-file-name "recipes" local-melpa-dir))
(setq package-build-working-dir (expand-file-name "working" local-melpa-dir))

(package-build-all)
```

Here are other things I have noticed:
- The output `Successfully built 0 of 1 packages` is right beside
  `Building 1 packages failed:`. Should there be an `\n` at the end of the
  `format` template [here](https://github.com/melpa/package-build/blob/master/package-build.el#L864)?
- Is it supposed to be `failed` instead of `invalid` [here](https://github.com/melpa/package-build/blob/master/package-build.el#L872)?

`package-build` commit: [0a22c3f](https://github.com/melpa/package-build/commit/0a22c3fbbf661822ec1791739953b937a12fa623)

**Comment by tarsius** [comment]
Sorry this took so long.
