### ISSUE TITLE
request not to use local time in package version

### ISSUE THREAD

**Issue by emacs18** [melpa/package-build#31]
It appears that the time string used in package name is
created based on *local time* rather than some fixed time
such as Greenwich time.  This is now causing problem, because
package that I built has different time string than the one
used by the official melpa packages.  For example I just got
the following error when I built all my packages myself:

  (Spacemacs) Error:
  An error occurred while installing ein
  (error: (error Need package ‘request-20190621.1622’, but only 20190621.922 is available))

The official package at melpa.org has 1622 as time string.
Package I built has 922 time string.  My time zone is UTC-7.

If package-build.el is modified so that it always uses Greenwich time
rather than local time in package version, then it appears that
I would not run into the problem just described.

**Comment by tarsius** [comment]
Yes... #30 :stuck_out_tongue_closed_eyes:
