### ISSUE TITLE
Doesn't recover from hard resets to older revisions

### ISSUE THREAD

**Issue by purcell** [melpa/package-build#39]
If a package is built, but then the upstream git repo's default branch is reset to an older revision, this confuses `package-build`: the correct (older) version is built, but `.entry` files then exist for both versions, and `package-build-dump-archive-contents` strictly prefers the higher version when building the full set of available packages.

An example of this problem is with `clang-format`, where MELPA [currently serves](package-build-dump-archive-contents) version 20191121.1708 for now-non-existent commit 2d6a45, while the latest built version is 20191106.950, for commit e48ff8a.

The solution is probably to always prefer the newest `.entry` file on disk, rather than the one with the highest version. Can you think of any issues with doing this, @tarsius?

/cc @adisbladis, who reported this to me, since it breaks downstream tooling that looks at metadata (including commits) for packages built by MELPA.

**Comment by tarsius** [comment]
Sounds reasonable and so far no issue has come to mind.

**Comment by purcell** [comment]
Done, pushed here, and grafted into MELPA for use in its builds. @adisbladis: the downstream issue should resolve itself now, but note that MELPA version numbers for a given package may not be assumed to increase monotonically.
