### ISSUE TITLE
Branch setting ignored?

### ISSUE THREAD

**Issue by jscheid** [melpa/package-build#53]
Is it possible that one of the recent changes - db227b020f2f8c0161eccec16cc9122e802ed543 perhaps? - causes the `branch` setting in the recipe to be ignored? My package appears to have broken recently and I'm hoping someone can help me figure out what's going on.

There's more info about the concrete problem in https://github.com/melpa/melpa/issues/7652 and https://github.com/jscheid/prettier.el/issues/90.

**Comment by tarsius** [comment]
Yes. I'll have to think about how to best fix this.

**Comment by tarsius** [comment]
You can find a tentative fix in the `chicken` (and egg) branch.

**Comment by jscheid** [comment]
Thanks, can I do anything to help make it land and get my package rebuilt?

**Comment by tarsius** [comment]
Well you could test it locally, but really I just have to write down the reasoning and test one more time myself.

**Comment by jscheid** [comment]
I've cloned the melpa repository and this one, checked out the chicken branch and copied over `package-build.el`, then ran this:

```
➜  melpa git:(master) ✗ make recipes/prettier
 • Building package prettier ...
Package: prettier
Fetcher: github
Source:  https://github.com/jscheid/prettier.el.git

Cloning https://github.com/jscheid/prettier.el.git to /melpa-test/melpa/working/prettier/
Checking out origin/release
Checking out e38d21a885e234af9ea6b03f499c487175570571
Copying files (->) and directories (=>)
  from /melpa-test/melpa/working/prettier/
  to /tmp/bp/ts3_80kx6f336zm34kjldcb40000gn/T/prettierDCFvFE/prettier-20210606.1152
    prettier.el -> prettier.el
    dir -> dir
    prettier.info -> prettier.info
    bootstrap-min.js -> bootstrap-min.js
    prettier-el.js.gz.base64 -> prettier-el.js.gz.base64
Created prettier-20210606.1152.tar containing:
  prettier-20210606.1152/
  prettier-20210606.1152/bootstrap-min.js
  prettier-20210606.1152/dir
  prettier-20210606.1152/prettier-el.js.gz.base64
  prettier-20210606.1152/prettier-pkg.el
  prettier-20210606.1152/prettier.el
  prettier-20210606.1152/prettier.info
Built prettier in 4.042s, finished at 2021-07-23T21:07:43+0000
 ✓ Success:
  8 -rw-r--r--  1 user  staff   439B Jul 24 09:07 packages/prettier-20210606.1152.entry
160 -rw-r--r--  1 user  staff    80K Jul 24 09:07 packages/prettier-20210606.1152.tar
  8 -rw-r--r--  1 user  staff   1.1K Jul 24 09:07 packages/prettier-badge.svg
  8 -rw-r--r--  1 user  staff   255B Jul 24 09:07 packages/prettier-readme.txt
```

That's looking good! It's the correct commit.

**Comment by tarsius** [comment]
Pushed here and to Melpa. Might take a few hours for Melpa to start using.

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by jscheid** [comment]
Seems to be working again, thanks!
