### ISSUE TITLE
 Allow timeout "command" to inherit variables || Make quelpa & package-build inherit GIT_EXEC_PATH variable

### ISSUE THREAD

**Issue by imme-emosol** [melpa/package-build#76]
"should ask melpa/package-build" ~ _posted in https://github.com/syl20bnr/spacemacs/issues/15933#issuecomment-1441516185_ "

Hi, I have a weird GIT-configuration to allow me to run some customized git programs by default.

However, the usual GIT_EXEC_PATH="/usr/lib/git-core" emacs did not work for spacemacs, perhaps because of the timeout wrap around git.

I can make the startup errors go away by replacing command in package-build--run-process ( core/libs/package-build.el ) & in quelpa-build--run-process ( core/libs/quelpa.el ) with: "env" "GIT_EXEC_PATH=/usr/lib/git-core" command

Would it be possible (and sensible) to allow variables to be "known" to the (git) command? So that, for example GIT_EXEC_PATH="/usr/lib/git-core" emacs would work.

**Comment by tarsius** [comment]
Did you add the directory where your custom `git` binary is installed to `$PATH` (not just in your shell but for Emacs as well)?

> Would it be possible (and sensible) to allow variables to be "known" to the (git) command?

I don't think it would be sensible for every package that calls `git` to add an option that would allow it to work with your apparently weird setup. It seems you have to figure out how to adjust your configuration to make it unnecessary to make changes elsewhere.

**Comment by imme-emosol** [comment]
I do not have a custom built git, in GIT_EXEC_PATH there are only custom builds of gitk & git-gui.

This requires me to work around "git's subcommand resolving" to run certain git-commands.
For instance for mergetool i execute the command: `GIT_EXEC_PATH="/usr/lib/git-core" git mergetool`

Which is why i expected `GIT_EXEC_PATH="/usr/lib/git-core" emacs` to work as well, but it does not, neither does `( export GIT_EXEC_PATH="/usr/lib/git-core" ; emacs )`

It gives me "git: 'remote-https' is not a git command.", which is probably because git is started with my default GIT_EXEC_PATH that is missing quite some git-programs, such as git-remote-https.

**Comment by imme-emosol** [comment]
Of course, feel free to close this issue if this is too strange a situation to take into account.

**Comment by tarsius** [comment]
> I do not have a custom built git, in GIT_EXEC_PATH there are only custom builds of gitk & git-gui.

At least the former is a binary. If the latter is too, it might be enough to symlink those into `$PATH`.

> This requires me to work around "git's subcommand resolving" to run certain git-commands.
For instance for mergetool i execute the command: `GIT_EXEC_PATH="/usr/lib/git-core" git mergetool`

I believe this should not be necessary. I am under the impression you go about it the wrong way. First make sure `git` works without requiring any shenanigans. Only then try making your custom build of secondary tools available.

> Of course, feel free to close this issue if this is too strange a situation to take into account.

Yeah, I don't think it makes sense to add any kludges to this package.
