### ISSUE TITLE
Compilation lint error re. use of rassq-delete-all

### ISSUE THREAD

**Issue by purcell** [melpa/package-build#82]
Hey @tarsius, I see that the build fails for emacs HEAD due to the following new compilation error:

```
Compiling package-build.el

In toplevel form:
package-build.el:1219:31: Error: value from call to ‘assq-delete-all’ is unused
make: *** [Makefile:32: package-build.elc] Error 1
```

I wasn't sure if the correct fix was just to assign the result back to the `let`-bound var locally, or if it indicates an issue with the logic. Any idea?

**Comment by tarsius** [comment]
Mostly harmless; but we are dealing with a wacky api and encoding issues, so its worth a few comments.

**Comment by purcell** [comment]
Nice, makes sense, thanks!
