### ISSUE TITLE
cyclic-variable-indirection package-build-write-badge-images

### ISSUE THREAD

**Issue by jcs090218** [melpa/package-build#83]
I recently got this error after the latest three commits 6223cae00a2e6c77864caaa3c5f84330d0ef2b93, 4381b1d7b2141eb60a2b9d494180a52dc7ec71bd and 6e48df3ac055ab98219165de0780c7822682c2f4. 🤔 

```
Debugger entered--Lisp error: (cyclic-variable-indirection package-build-write-badge-images)
  set-default-toplevel-value(package-build-write-badge-images nil)
  custom-initialize-reset(package-build-write-badge-images (funcall #'(closure (t) nil "" nil)))
  custom-declare-variable(package-build-write-badge-images (funcall #'(closure (t) nil "" nil)) "When non-nil, write badge images alongside package..." :group package-build :type boolean)
  eval-buffer(#<buffer  *load*-543564> nil "/home/runner/work/jcs-elpa/jcs-elpa/.eask/28.2/elp..." nil t)  ; Reading at buffer position 6611
  load-with-code-conversion("/home/runner/work/jcs-elpa/jcs-elpa/.eask/28.2/elp..." "/home/runner/work/jcs-elpa/jcs-elpa/.eask/28.2/elp..." nil t)
  require(package-build)
  eval-buffer(#<buffer  *load*-401696> nil "/home/runner/work/jcs-elpa/jcs-elpa/.eask/28.2/elp..." nil t)  ; Reading at buffer position [20](https://github.com/jcs-emacs/jcs-elpa/actions/runs/5152804123/jobs/9279298809#step:6:21)63
  load-with-code-conversion("/home/runner/work/jcs-elpa/jcs-elpa/.eask/28.2/elp..." "/home/runner/work/jcs-elpa/jcs-elpa/.eask/28.2/elp..." t t)
  require(github-elpa nil t)
```

See full log https://github.com/jcs-emacs/jcs-elpa/actions/runs/5152804123/jobs/9279298809#step:6:18.

**Comment by jcs090218** [comment]
I don't think MELPA will build packages since it would face the same issue.

**Comment by tarsius** [comment]
The commit that I pushed didn't fix the issue for you?

**Comment by jcs090218** [comment]
I mean you haven't pushed the commit to MELPA, so MELPA wouldn't update any packages. See the MELPA page, the latest update package is hypedrive 20230601.714 (I checked that yesterday, pretty sure it's stucked).

For me, JCS-ELPA grabs package-build from MELPA so no, JCS-ELPA is still broken.

**Comment by tarsius** [comment]
Ah right, I thought I had not merged the faulty version into Melpa yet.

**Comment by tarsius** [comment]
Thanks for letting me know!

**Comment by jcs090218** [comment]
Thank you! ;)

**Comment by jcs090218** [comment]
BTW, does MELPA have a system to inform maintainers that the server isn't building packages? Maybe that would help to reduce the downtime? Just a whim. ;)
