### ISSUE TITLE
Maybe sort `.eld` entries?

### ISSUE THREAD

**Issue by jcs090218** [melpa/package-build#85]
Hi, [JCS-ELPA](https://github.com/jcs-emacs/jcs-elpa) will keep updating the `elpa-packages.eld` file no matter whether the packages have changed or not. 🤔 

![2023-10-01 15 03 47](https://github.com/melpa/package-build/assets/8685505/de612516-91df-43b2-9367-dd0027421648)

Is there a way to make it consistent? Maybe something similar to `cl-sort` on `archive-contents`'s entries:

https://github.com/melpa/package-build/blob/a60f0b539b5f85f1a45c4ae2e0dc9a5ffbe091fa/package-build.el#L1581-L1582

**Comment by tarsius** [comment]
Thanks for the suggestion!
