### ISSUE TITLE
Quotation marks in package description lead to malformed '*-pkg.el'

### ISSUE THREAD

**Issue by pengjiz** [melpa/package-build#90]
Hi!

It seems that if the description in the source file contains quotation mark `"`, the generated package cannot be installed because they are not escaped. E.g., for `ledger-mode`:

```emacs-lisp
;;; ledger-mode.el --- Helper code for use with the "ledger" command-line tool  -*- lexical-binding: t; -*-
```

the generated 'ledger-mode-pkg.el' is:

```emacs-lisp
(define-package "ledger-mode" "20240804.1623"
  "Helper code for use with the "ledger" command-line tool."
  ...)
```

which is malformed.

Presumably it is a2b2a790f99e0c5150a53507dfe868e54d0d9a6e?

Thanks!

**Comment by tarsius** [comment]
Thanks for the report!

The fixed builds should be available in a few hours.

**Comment by purcell** [comment]
Thanks for the quick fix, @tarsius, I saw a different report about this too. It affects 39 packages currently: https://melpa.org/#/?q=%22

**Comment by pengjiz** [comment]
AFAICT it is indeed fixed. Thank you for your quick response!
